name: Lint and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'      
        
jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Verificar Lint
        run: npm run lint

      - name: Executar Testes
        run: npm run test
